In [1]:
import pandas as pd
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

In [10]:
api_key = "AIzaSyAX0WBz3m3kDwHrEh25gOrPmeYWUIUlSWo"
api_service_name = 'youtube'
api_version = 'v3'
youtube=build(api_service_name, api_version, developerKey=api_key)

In [20]:
def Channel_id(channel_id):
    raw_data=[]
    api_key = "AIzaSyD6a-fcovIUsEx_x54oJqxR7Kp6W_E2dqw"
    api_service_name = 'youtube'
    api_version = 'v3'
    youtube=build(api_service_name, api_version, developerKey=api_key)
    get_data=youtube.channels().list(part="snippet,contentDetails,statistics",id=channel_id)
    request=get_data.execute()
    for item in request["items"]:
        data={'channelName':item["snippet"]["title"],
             'subcription':item["statistics"]["subscriberCount"],
             'views':item["statistics"]["viewCount"],
             'total_videos':item["statistics"]["videoCount"],
             'playlist_id':item["contentDetails"]["relatedPlaylists"]["uploads"]}
        raw_data.append(data)
    return(pd.DataFrame(raw_data))
cid=input("channel ID")
Channel_id(cid)
#Channel_id("UCnKhQkCUS1oCEvjuTfU4xIw")

channel IDUCnKhQkCUS1oCEvjuTfU4xIw

  channelName subcription      views total_videos               playlist_id
0   Tech Boss     3740000  883630625         1407  UUnKhQkCUS1oCEvjuTfU4xIw

In [21]:
raw_data1=[]
api_key = "AIzaSyBsYY3Vysqe8dbuvalGLLECqh3960Gqahc"
api_service_name = 'youtube'
api_version = 'v3'
youtube=build(api_service_name, api_version, developerKey=api_key)
get_data=youtube.channels().list(
    part="snippet,contentDetails,statistics",
    #id ='UCnKhQkCUS1oCEvjuTfU4xIw')
    id =cid)
request=get_data.execute()

for item in request["items"]:
    data={'channel_id':item["id"],
            'channelName':item["snippet"]["title"],
             'subcription':item["statistics"]["subscriberCount"],
             'views':item["statistics"]["viewCount"],
             'total_videos':item["statistics"]["videoCount"],
             'playlist_id':item["contentDetails"]["relatedPlaylists"]["uploads"],
             'description':item["snippet"]["description"],
              'publishedAt':item["snippet"]["publishedAt"],
              'viewCount':item["statistics"]["viewCount"]}
    raw_data1.append(data)
    
pd.DataFrame(raw_data1)

,channel_id,channelName,subcription,views,total_videos,playlist_id,description,publishedAt,viewCount
0,UCnKhQkCUS1oCEvjuTfU4xIw,Tech Boss,3740000,883630625,1407,UUnKhQkCUS1oCEvjuTfU4xIw,Tech Boss Channel is an authentic where you ca...,2018-04-12T04:49:58Z,883630625

In [23]:
playlist_id= "UUnKhQkCUS1oCEvjuTfU4xIw"
#playlist_id=cid
def Channel_vid(youtube,playlist_id):
    vid_data=[]
    get_data=youtube.playlistItems().list(part="snippet,contentDetails",
                            playlistId=playlist_id, maxResults=40)
    request=get_data.execute()
    for item in request["items"]:
        vid_data.append(item["contentDetails"]["videoId"])
    next_page=request.get("nextPageToken")
    while next_page is not None:
        get_data=youtube.playlistItems().list(
                part='contentDetails',
                playlistId=playlist_id, 
                maxResults=40,
                pageToken = next_page)
        request=get_data.execute()
        for item in request["items"]:
            vid_data.append(item["contentDetails"]["videoId"])
        next_page=request.get("nextPageToken")
    return vid_data
vid_data = Channel_vid(youtube,playlist_id)

In [24]:
len(vid_data)

1408

In [25]:
def video_info(youtube,vid_data):
    vid_info=[]
    for i in range(0, len(vid_data),40):
        get_data=youtube.videos().list(
            part="snippet,contentDetails,statistics",
            id=','.join(vid_data[i:i+40]))
        value=get_data.execute()
        for vid in value['items']:
            details={'snippet':['chennelTitle','Title','description','tags','publishedAt'],
                    'statistics':['viewCount','likeCount','favouriteCount','commentCount'],
                    'contentDetails':['duration','definition','caption']
                    }
            info={}
            info['video_id']= vid['id']
            for j in details.keys():
                for k in details[j]:
                    try:
                        info[k] = vid[j][k]
                    except:
                        info[k] = None
            vid_info.append(info)
    return pd.DataFrame(vid_info)
vid_df = video_info(youtube,vid_data)

In [26]:
vid_df

,video_id,chennelTitle,Title,description,tags,publishedAt,viewCount,likeCount,favouriteCount,commentCount,duration,definition,caption
0,Ad-xWVaohVQ,None,None,---\nMedia Partner : Adada Creators\nEmail : t...,[Techboss],2023-05-17T04:31:00Z,147277,32833,None,102,PT59S,hd,false
1,6zjB74XbDs8,None,None,---\nMedia Partner : Adada Creators\nEmail : t...,[Techboss],2023-05-16T11:00:47Z,456594,47608,None,496,PT19S,hd,false
2,4XAw4yUMWYU,None,None,---\nMedia Partner : Adada Creators\nEmail : t...,[Techboss],2023-05-15T06:04:30Z,555502,74997,None,290,PT37S,hd,false
3,6rBtYBtrhwA,None,None,---\nMedia Partner : Adada Creators\nEmail : t...,[Techboss],2023-05-13T11:34:00Z,774937,91646,None,255,PT42S,hd,false
4,M6qK-Q6pKdM,None,None,#TecnoPhantomVFold #TechBoss #Tecno \n\n---\nM...,"[Techboss, Tecno Phantom V Fold, Cheapest Fold...",2023-05-13T03:54:24Z,330657,15453,None,732,PT10M5S,hd,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,5jQsr0PfNCQ,None,None,Best Buy Link : http://fkrt.it/ci4k2KNNNN\n\nஒ...,"[Jio, Unboxing & Review, Asus Zenfone Max, Zen...",2018-05-05T08:23:41Z,9678,361,None,40,PT10M7S,hd,false
1404,HUYng0m8DC8,None,None,Engineering Counsellingக்கு ஆன்லைனில் அப்பளை ச...,"[Engineering Counselling, tnea 2018, tnea appl...",2018-05-04T12:53:52Z,3319,134,None,15,PT5M38S,hd,false
1405,ztLI7LGJbG8,None,None,Best Buy Link:\n\nBlackt Electrotech : (BT81D)...,"[Home Automation, Unboxing, sensor light, sens...",2018-05-04T06:19:32Z,49251,871,None,35,PT2M51S,hd,false
1406,vBqO4gCIEKk,None,None,Buy Here:\nhttps://goo.gl/93Hesu\nhttps://goo....,"[Unboxing & Review, FeiyuTech Vimble 2, Unboxi...",2018-05-02T06:20:42Z,21834,757,None,52,PT6M39S,hd,false
1407,HRxA_kAVBFM,None,None,Link : https://amzn.to/2vG61ej\n\nUnboxing & R...,"[Unboxing & Review, Zoom H1 Recorder, Digital ...",2018-04-26T02:31:09Z,44338,2737,None,263,PT6M8S,hd,false

In [17]:
 def vid_comments(youtube, vid_data):
    all_com = []
    for i in vid_data:
        try:
            val = youtube.commentThreads().list(
                part="snippet,replies",
                videoId=i,
                maxResults=10
            )

            data = val.execute()
            if 'items' in data:
                all_comments = [j['snippet']['topLevelComment']['snippet']['textOriginal'] for j in data['items']]
            else:
                all_comments = None
            comments_data = {'video_id': i, 'comments': all_comments}
            all_com.append(comments_data)
        except HttpError as e:
            if e.resp.status in [403, 400]:
                comments_data = {'video_id': i, 'comments': None}
                all_com.append(comments_data)
            else:
                raise e
    return pd.DataFrame(all_com)
all_com = vid_comments(youtube, vid_data)
all_com

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

         video_id                                           comments
0     Ad-xWVaohVQ  [Semma akka neega 👌🤣🤭, Vera level bro😊, Adei c...
1     6zjB74XbDs8  [Anna neenga soniga la adhu na panni padhan an...
2     4XAw4yUMWYU  [x90 ku x80 pottu irukkiye bro😂😂🎉, when we for...
3     6rBtYBtrhwA  [😂😂😂😂, Full video podu nga, just now bought th...
4     M6qK-Q6pKdM  [Plsssss 😢whatspp database yepdi recovery panu...
...           ...                                                ...
1403  5jQsr0PfNCQ  [Currently I am using same Asus Zenfone max 1 ...
1404  HUYng0m8DC8  [Hi, Old tech boss to current tech boss awesom...
1405  ztLI7LGJbG8  [Intha video yanakku ippo recommend aaguthu 4 ...
1406  vBqO4gCIEKk  [3.m, வாழ்த்துக்கள்🎉🎊🎉🎊🎉🎊🎉🎊, Bro mobile la joy...
1407  HRxA_kAVBFM  [Waiting now for a new YouTube vlog idea.. 17t...

[1408 rows x 2 columns]

In [18]:
vid_comments = pd.DataFrame(all_com)

In [19]:
vid_comments.head()

      video_id                                           comments
0  Ad-xWVaohVQ  [Semma akka neega 👌🤣🤭, Vera level bro😊, Adei c...
1  6zjB74XbDs8  [Anna neenga soniga la adhu na panni padhan an...
2  4XAw4yUMWYU  [x90 ku x80 pottu irukkiye bro😂😂🎉, when we for...
3  6rBtYBtrhwA  [😂😂😂😂, Full video podu nga, just now bought th...
4  M6qK-Q6pKdM  [Plsssss 😢whatspp database yepdi recovery panu...